image: ubuntu:xenial
stages:
  - build

build:
  stage: build
  script:
    - git clone https://github.com/osresearch/heads
    - cd heads
    - make BOARD=x230
  artifacts:
    paths:
      - heads/build/x230/coreboot.rom

