image: nemanjan00/heads-ci:latest
stages:
  - build

build:
  stage: build
  cache:
    paths:
      - heads/
  script:
    - ./gitorclone.sh https://github.com/osresearch/heads heads
    - cd heads
    - make BOARD=x230
    - sed -e '/CONFIG_GPG/ s/^#*/#/' -i boards/x230-flash/x230-flash.config
    - make BOARD=x230-flash
    - make BOARD=qemu-linuxboot
    - make BOARD=qemu-coreboot
  artifacts:
    paths:
      - heads/build/x230/coreboot.rom
      - heads/build/x230-flash/coreboot.rom
      - heads/build/qemu-linuxboot/linuxboot.rom
      - heads/build/qemu-coreboot/coreboot.rom

