image: nemanjan00/heads-ci:latest
stages:
  - build

build:
  stage: build
  cache:
    paths:
      - heads/
  script:
    - ./gitorclone.sh https://github.com/osresearch/heads heads
    - cd heads
    - make BOARD=x230
    - make BOARD=x230-flash
  artifacts:
    paths:
      - heads/build/x230/coreboot.rom
      - heads/build/x230-flash/x230-flash.rom
