image: insurgotech/heads-ci:latest
stages:
  - build

build:
  stage: build
  cache:
    paths:
      - heads/
  script:
    - ./gitorclone.sh https://github.com/tlaurion/heads heads
    - cd heads
    - git checkout oem_reownership-staging
    - make BOARD=x230-flash
    - make BOARD=x230
  artifacts:
    paths:
      - heads/build/x230-flash/x230-flash.rom
      - heads/build/x230/coreboot.rom
